### ISSUE TITLE
When using custom geometry with forward-shading, TEXCOORD is required.

### ISSUE THREAD

**Issue by cx20** [GrimoireGL/grimoirejs-forward-shading#5]
Please do not require TEXCOORD for geometry using Vertex Color.

**Comment by kyasbal** [comment]
I have not understand this issue well.
Vertexlit is not supported on forward-shading shader.
You should probably need to rewrite some shaders if you really need to use vertex color.

However, I haven't implemented the feature to recognize what attribute variables are passed to geometry in macro syntax of '.sort'. Once that have been implemented, It is very easy thing to generate TEXCOORD from POSITION only if that was not provided.

**Comment by cx20** [comment]
Please refer to the sample below for this Issue.
http://jsdo.it/cx20/8EUP
![image](https://cloud.githubusercontent.com/assets/1833979/25335410/db937c8e-292d-11e7-9b9e-afe204b8f0ae.png)

I think the following results are correct.
![image](https://cloud.githubusercontent.com/assets/1833979/25335369/acd0e788-292d-11e7-8763-9d7afd2f978b.png)
